version: "3"
services:
  ehbot:
    build: .
    container_name: ehbot
    restart: always
    network_mode: "host"
    environment:
      CONFIG_FILE: "/config.yaml"
      TZ: Asia/Shanghai
    volumes:
      - "./config.yaml:/config.yaml:ro"
    logging:
      driver: journald